[config]
schemaVersion = "0.0.1"

[package]
namespace = "Mehaz"
name = "ExtendedAltarOfAshes"
versionNumber = "1.1.2"
description = "Adds Heroic and Legendary upgrades to the Altar of Ashes cards and increases maximum Grasp."
websiteUrl = "https://github.com/gabrielmarx13/ExtendedAltarOfAshes"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-DemonDaemon = "1.0.1"
SGG_Modding-ModUtil = "3.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]